# Generated by Django 3.2 on 2021-05-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toys', '0002_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('Image', models.ImageField(unique=True, upload_to='images/')),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(max_length=20)),
                ('Description', models.CharField(blank=True, max_length=50)),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
